### PR TITLE
Lots of highlighting improvements

### PR DESCRIPTION
**Pull request by MattFryer**
Made a huge number of improvements to the highlighting including:
* all join and keeps statements
* load distinct
* info and bundle info loads
* noconcatenate
* direct query statements
* logic statements (sub routines, switch statements, for and do loops) 
* REM comments
* call statements
* end script statements
* a large number of functions

There are quite a lot of functions still to add and there are a few problems with keywords highlighting when they shouldn't and not when they should. It's a good start though.

If you decide to push this out to the VS marketplace, let me know and I'll get a blog post up on QlikViewAddict.com to get it some coverage.

### CODE REVIEW

**Comment by Gimly** [comment]
I don't mind much the missing keywords, but I'd rather that we have the issues of keywords being wrongly highlighted before we push to the marketplace. Do you have some tests that show those issues?

**Comment by MattFryer** [comment]
I've just made a new commit that solves all the ones I've found so far.  I've been using this test script which I use for my other language definitions. https://github.com/MattFryer/Qlik-Web-Highlight/blob/master/development/test-scripts/test%20script.qvs It's not an exhaustive script but covers most commonly used things.

**Comment by Gimly** [comment]
Awesome, I'm going to do a quick test, merge your PR and push the new version to the marketplace. Thanks a lot for that contribution!

**Comment by MattFryer** [comment]
No problem. I'll get a post up once its available on the marketplace.

When I find a bit more time I'll make some more improvements.

**Comment by Gimly** [comment]
Hey Matt,

Just to let you know, the new veryion is available on the Marketplace, with version 0.4.0.

Thanks again for your help!

Cheers,
Xavier

**Pull request merged**
